version: '洛业LY:2.0.0:'
projects:
- G:\project\try_segmentlabel
- G:\project\p6
- G:\project\p8
current_project: G:\project\p8
default_dir: G:/project/p8
default_file: G:\project\p8\experiments\p1\weights
style: technology
