task: detect
mode: v5
weights: yolov5s.pt
cfg: ''
data: ''
hyp: v5_hyp.yaml
epochs: 100
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: 300
evolve_population: ''
resume_evolve: ''
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
no_overlap: true
mask_ratio: 4

#val
save_json: false
split: val
save_hybrid: false
conf_thres: 0.5
iou_thres: 0.2
max_det: 300
half: false
dnn: false

#predict
source: 选中图像
vid_stride: 1
visualize: false
augment: false
agnostic_nms: false
classes: None
retina_mask: false

#export
format: ONNX
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: 10
workspace: 4
nms: false

#visualize
view_img: false
save_txt: false
save_conf: false
save_format: 0
save_csv: false
save_crop: false
hide_labels: true
hide_conf: false
line_thickness: 3


