# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'trainQT备份1.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDockWidget, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLayout, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QRadioButton, QSizePolicy, QSpacerItem, QSplitter,
    QStatusBar, QTabWidget, QTextEdit, QToolBar,
    QTreeWidget, QTreeWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1057, 743)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.Train_a = QAction(MainWindow)
        self.Train_a.setObjectName(u"Train_a")
        icon = QIcon()
        icon.addFile(u":/aa/F:/Download_icon/MdiBulma.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Train_a.setIcon(icon)
        self.Val_a = QAction(MainWindow)
        self.Val_a.setObjectName(u"Val_a")
        self.Predict_a = QAction(MainWindow)
        self.Predict_a.setObjectName(u"Predict_a")
        self.Export_a = QAction(MainWindow)
        self.Export_a.setObjectName(u"Export_a")
        self.New_project_a = QAction(MainWindow)
        self.New_project_a.setObjectName(u"New_project_a")
        self.Open_project_a = QAction(MainWindow)
        self.Open_project_a.setObjectName(u"Open_project_a")
        self.Save_a = QAction(MainWindow)
        self.Save_a.setObjectName(u"Save_a")
        self.Save_as_a = QAction(MainWindow)
        self.Save_as_a.setObjectName(u"Save_as_a")
        self.Exit_a = QAction(MainWindow)
        self.Exit_a.setObjectName(u"Exit_a")
        self.Back_start_a = QAction(MainWindow)
        self.Back_start_a.setObjectName(u"Back_start_a")
        self.Edit_net_a = QAction(MainWindow)
        self.Edit_net_a.setObjectName(u"Edit_net_a")
        self.Show_args_a = QAction(MainWindow)
        self.Show_args_a.setObjectName(u"Show_args_a")
        self.Show_allargs_a = QAction(MainWindow)
        self.Show_allargs_a.setObjectName(u"Show_allargs_a")
        self.Show_allargs_a.setCheckable(True)
        self.Show_confusion_a = QAction(MainWindow)
        self.Show_confusion_a.setObjectName(u"Show_confusion_a")
        self.Show_result_curve_a = QAction(MainWindow)
        self.Show_result_curve_a.setObjectName(u"Show_result_curve_a")
        self.Show_progress_a = QAction(MainWindow)
        self.Show_progress_a.setObjectName(u"Show_progress_a")
        self.New_experiment_a = QAction(MainWindow)
        self.New_experiment_a.setObjectName(u"New_experiment_a")
        self.Open_experiment_a = QAction(MainWindow)
        self.Open_experiment_a.setObjectName(u"Open_experiment_a")
        self.Show_sift_image_a = QAction(MainWindow)
        self.Show_sift_image_a.setObjectName(u"Show_sift_image_a")
        self.Cfgs_init_a = QAction(MainWindow)
        self.Cfgs_init_a.setObjectName(u"Cfgs_init_a")
        self.Load_dataset_a = QAction(MainWindow)
        self.Load_dataset_a.setObjectName(u"Load_dataset_a")
        self.Create_dataset_a = QAction(MainWindow)
        self.Create_dataset_a.setObjectName(u"Create_dataset_a")
        self.Load_zip_a = QAction(MainWindow)
        self.Load_zip_a.setObjectName(u"Load_zip_a")
        self.Add_no_label_a = QAction(MainWindow)
        self.Add_no_label_a.setObjectName(u"Add_no_label_a")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_7 = QGridLayout(self.centralwidget)
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(1, 1, 1, 1)
        self.Source_show_f = QFrame(self.centralwidget)
        self.Source_show_f.setObjectName(u"Source_show_f")
        self.Source_show_f.setStyleSheet(u"")
        self.Source_show_f.setFrameShape(QFrame.Box)
        self.Source_show_f.setFrameShadow(QFrame.Raised)

        self.gridLayout_7.addWidget(self.Source_show_f, 1, 0, 1, 1)

        self.Painter_tool_f = QFrame(self.centralwidget)
        self.Painter_tool_f.setObjectName(u"Painter_tool_f")
        self.Painter_tool_f.setMinimumSize(QSize(0, 0))
        self.Painter_tool_f.setMaximumSize(QSize(16777215, 40))
        self.Painter_tool_f.setStyleSheet(u"background-color: rgb(247, 255, 246);")
        self.Painter_tool_f.setFrameShape(QFrame.Box)
        self.Painter_tool_f.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.Painter_tool_f)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.line = QFrame(self.Painter_tool_f)
        self.line.setObjectName(u"line")
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout_4.addWidget(self.line)

        self.Tool_show_pred_pb = QPushButton(self.Painter_tool_f)
        self.Tool_show_pred_pb.setObjectName(u"Tool_show_pred_pb")
        self.Tool_show_pred_pb.setMinimumSize(QSize(0, 0))
        self.Tool_show_pred_pb.setMaximumSize(QSize(30, 16777215))
        font = QFont()
        font.setFamilies([u"\u5b8b\u4f53"])
        font.setPointSize(14)
        self.Tool_show_pred_pb.setFont(font)
        self.Tool_show_pred_pb.setStyleSheet(u"background-color: rgba(255, 255, 255);")

        self.horizontalLayout_4.addWidget(self.Tool_show_pred_pb)

        self.Tool_show_true_pb = QPushButton(self.Painter_tool_f)
        self.Tool_show_true_pb.setObjectName(u"Tool_show_true_pb")
        self.Tool_show_true_pb.setMinimumSize(QSize(0, 0))
        self.Tool_show_true_pb.setMaximumSize(QSize(30, 16777215))
        self.Tool_show_true_pb.setFont(font)
        self.Tool_show_true_pb.setStyleSheet(u"background-color: rgba(255, 255, 255);")

        self.horizontalLayout_4.addWidget(self.Tool_show_true_pb)

        self.line_2 = QFrame(self.Painter_tool_f)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(20)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout_4.addWidget(self.line_2)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_3)

        self.widget_4 = QWidget(self.Painter_tool_f)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setEnabled(True)
        self.horizontalLayout_3 = QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.Tool_train_rb = QRadioButton(self.widget_4)
        self.Tool_train_rb.setObjectName(u"Tool_train_rb")
        self.Tool_train_rb.setEnabled(False)
        self.Tool_train_rb.setCheckable(True)

        self.horizontalLayout_3.addWidget(self.Tool_train_rb)

        self.Tool_val_rb = QRadioButton(self.widget_4)
        self.Tool_val_rb.setObjectName(u"Tool_val_rb")
        self.Tool_val_rb.setEnabled(False)
        self.Tool_val_rb.setCheckable(True)

        self.horizontalLayout_3.addWidget(self.Tool_val_rb)

        self.Tool_no_label_rb = QRadioButton(self.widget_4)
        self.Tool_no_label_rb.setObjectName(u"Tool_no_label_rb")
        self.Tool_no_label_rb.setEnabled(False)
        self.Tool_no_label_rb.setCheckable(True)

        self.horizontalLayout_3.addWidget(self.Tool_no_label_rb)

        self.Tool_results_rb = QRadioButton(self.widget_4)
        self.Tool_results_rb.setObjectName(u"Tool_results_rb")
        self.Tool_results_rb.setEnabled(False)
        self.Tool_results_rb.setCheckable(True)

        self.horizontalLayout_3.addWidget(self.Tool_results_rb)


        self.horizontalLayout_4.addWidget(self.widget_4)


        self.gridLayout_7.addWidget(self.Painter_tool_f, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1057, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menunew = QMenu(self.menu)
        self.menunew.setObjectName(u"menunew")
        self.menuopen = QMenu(self.menu)
        self.menuopen.setObjectName(u"menuopen")
        self.Edit_menu = QMenu(self.menubar)
        self.Edit_menu.setObjectName(u"Edit_menu")
        self.Classes_menu = QMenu(self.Edit_menu)
        self.Classes_menu.setObjectName(u"Classes_menu")
        self.Dataset_menu = QMenu(self.Edit_menu)
        self.Dataset_menu.setObjectName(u"Dataset_menu")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menuarg = QMenu(self.menu_3)
        self.menuarg.setObjectName(u"menuarg")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.Progress_dw = QDockWidget(MainWindow)
        self.Progress_dw.setObjectName(u"Progress_dw")
        self.Progress_dw.setAllowedAreas(Qt.BottomDockWidgetArea|Qt.TopDockWidgetArea)
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.gridLayout_5 = QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.Tip_te = QTextEdit(self.dockWidgetContents_3)
        self.Tip_te.setObjectName(u"Tip_te")
        self.Tip_te.setStyleSheet(u"background-color: rgb(248, 255, 255);")
        self.Tip_te.setFrameShape(QFrame.Box)

        self.gridLayout_5.addWidget(self.Tip_te, 0, 0, 1, 1)

        self.frame_3 = QFrame(self.dockWidgetContents_3)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.gridLayout_4 = QGridLayout(self.frame_3)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.Batch_mes_le = QLineEdit(self.frame_3)
        self.Batch_mes_le.setObjectName(u"Batch_mes_le")
        font1 = QFont()
        font1.setFamilies([u"\u5b8b\u4f53"])
        font1.setPointSize(12)
        self.Batch_mes_le.setFont(font1)

        self.gridLayout_4.addWidget(self.Batch_mes_le, 1, 0, 1, 2)

        self.Run_message_te = QTextEdit(self.frame_3)
        self.Run_message_te.setObjectName(u"Run_message_te")
        self.Run_message_te.setFont(font1)
        self.Run_message_te.setStyleSheet(u"background-color: rgb(246, 254, 255);")

        self.gridLayout_4.addWidget(self.Run_message_te, 0, 1, 1, 1)


        self.gridLayout_5.addWidget(self.frame_3, 0, 1, 1, 1)

        self.Progress_b = QProgressBar(self.dockWidgetContents_3)
        self.Progress_b.setObjectName(u"Progress_b")
        self.Progress_b.setMaximum(100)
        self.Progress_b.setValue(0)

        self.gridLayout_5.addWidget(self.Progress_b, 1, 0, 1, 2)

        self.gridLayout_5.setColumnStretch(0, 5)
        self.gridLayout_5.setColumnStretch(1, 3)
        self.Progress_dw.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.Progress_dw)
        self.Result_curve_dw = QDockWidget(MainWindow)
        self.Result_curve_dw.setObjectName(u"Result_curve_dw")
        self.dockWidgetContents_4 = QWidget()
        self.dockWidgetContents_4.setObjectName(u"dockWidgetContents_4")
        self.gridLayout_6 = QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
        self.Show_results_f = QFrame(self.dockWidgetContents_4)
        self.Show_results_f.setObjectName(u"Show_results_f")
        self.Show_results_f.setStyleSheet(u"background-color: rgb(255, 255, 243);")
        self.Show_results_f.setFrameShape(QFrame.Box)
        self.Show_results_f.setFrameShadow(QFrame.Raised)

        self.gridLayout_6.addWidget(self.Show_results_f, 0, 0, 1, 1)

        self.Result_curve_dw.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.Result_curve_dw)
        self.Args_dw = QDockWidget(MainWindow)
        self.Args_dw.setObjectName(u"Args_dw")
        self.Args_dw.setFloating(False)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.Cfg_tw = QTreeWidget(self.dockWidgetContents)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.Cfg_tw.setHeaderItem(__qtreewidgetitem)
        self.Cfg_tw.setObjectName(u"Cfg_tw")
        self.Cfg_tw.setStyleSheet(u"QTreeView::item{\n"
"    padding:3px;\n"
"}")

        self.gridLayout.addWidget(self.Cfg_tw, 0, 0, 1, 1)

        self.Args_dw.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.Args_dw)
        self.Confusion_dw = QDockWidget(MainWindow)
        self.Confusion_dw.setObjectName(u"Confusion_dw")
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.gridLayout_2 = QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.tabWidget = QTabWidget(self.dockWidgetContents_2)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setStyleSheet(u"background-color: rgb(253, 255, 244);")
        self.Confusion_denorm_w = QWidget()
        self.Confusion_denorm_w.setObjectName(u"Confusion_denorm_w")
        self.tabWidget.addTab(self.Confusion_denorm_w, "")
        self.Confusion_norm_w = QWidget()
        self.Confusion_norm_w.setObjectName(u"Confusion_norm_w")
        self.tabWidget.addTab(self.Confusion_norm_w, "")

        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.Confusion_dw.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.Confusion_dw)
        self.Sift_image_dw = QDockWidget(MainWindow)
        self.Sift_image_dw.setObjectName(u"Sift_image_dw")
        self.dockWidgetContents_5 = QWidget()
        self.dockWidgetContents_5.setObjectName(u"dockWidgetContents_5")
        self.horizontalLayout_6 = QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.Sift_f = QFrame(self.dockWidgetContents_5)
        self.Sift_f.setObjectName(u"Sift_f")
        self.Sift_f.setFrameShape(QFrame.StyledPanel)
        self.Sift_f.setFrameShadow(QFrame.Raised)
        self.gridLayout_8 = QGridLayout(self.Sift_f)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(1, 1, 1, 1)
        self.Select_image_spliter = QSplitter(self.Sift_f)
        self.Select_image_spliter.setObjectName(u"Select_image_spliter")
        self.Select_image_spliter.setOrientation(Qt.Horizontal)
        self.Image_select_f = QFrame(self.Select_image_spliter)
        self.Image_select_f.setObjectName(u"Image_select_f")
        self.Image_select_f.setMinimumSize(QSize(0, 0))
        self.Image_select_f.setStyleSheet(u"background-color: rgb(247, 253, 255);")
        self.Image_select_f.setFrameShape(QFrame.Box)
        self.Image_select_f.setFrameShadow(QFrame.Raised)
        self.Select_image_spliter.addWidget(self.Image_select_f)
        self.Sift_gb = QGroupBox(self.Select_image_spliter)
        self.Sift_gb.setObjectName(u"Sift_gb")
        self.Sift_gb.setMaximumSize(QSize(1677215, 16777215))
        self.Sift_gb.setFont(font1)
        self.Sift_gb.setStyleSheet(u"background-color: rgb(247, 254, 255);")
        self.Sift_gb.setFlat(True)
        self.Sift_gb.setCheckable(False)
        self.gridLayout_3 = QGridLayout(self.Sift_gb)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.widget_5 = QWidget(self.Sift_gb)
        self.widget_5.setObjectName(u"widget_5")
        self.horizontalLayout_5 = QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.Select_ops_cbb = QComboBox(self.widget_5)
        self.Select_ops_cbb.addItem("")
        self.Select_ops_cbb.addItem("")
        self.Select_ops_cbb.addItem("")
        self.Select_ops_cbb.addItem("")
        self.Select_ops_cbb.setObjectName(u"Select_ops_cbb")
        font2 = QFont()
        font2.setFamilies([u"Agency FB"])
        font2.setPointSize(12)
        self.Select_ops_cbb.setFont(font2)

        self.horizontalLayout_5.addWidget(self.Select_ops_cbb)

        self.Select_all_pb = QPushButton(self.widget_5)
        self.Select_all_pb.setObjectName(u"Select_all_pb")
        self.Select_all_pb.setMaximumSize(QSize(40, 16777215))
        self.Select_all_pb.setFont(font2)

        self.horizontalLayout_5.addWidget(self.Select_all_pb)

        self.Select_batch_ops_pb = QPushButton(self.widget_5)
        self.Select_batch_ops_pb.setObjectName(u"Select_batch_ops_pb")
        self.Select_batch_ops_pb.setFont(font2)

        self.horizontalLayout_5.addWidget(self.Select_batch_ops_pb)

        self.horizontalLayout_5.setStretch(0, 10)
        self.horizontalLayout_5.setStretch(2, 5)

        self.gridLayout_3.addWidget(self.widget_5, 2, 0, 1, 1)

        self.widget_2 = QWidget(self.Sift_gb)
        self.widget_2.setObjectName(u"widget_2")
        self.gridLayout_9 = QGridLayout(self.widget_2)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setHorizontalSpacing(0)
        self.gridLayout_9.setVerticalSpacing(10)
        self.gridLayout_9.setContentsMargins(2, 2, 2, 2)
        self.Select_dataset_cbb = QComboBox(self.widget_2)
        self.Select_dataset_cbb.addItem("")
        self.Select_dataset_cbb.addItem("")
        self.Select_dataset_cbb.addItem("")
        self.Select_dataset_cbb.addItem("")
        self.Select_dataset_cbb.addItem("")
        self.Select_dataset_cbb.setObjectName(u"Select_dataset_cbb")
        self.Select_dataset_cbb.setFont(font1)

        self.gridLayout_9.addWidget(self.Select_dataset_cbb, 0, 1, 1, 1)

        self.Select_class_cbb = QComboBox(self.widget_2)
        self.Select_class_cbb.addItem("")
        self.Select_class_cbb.setObjectName(u"Select_class_cbb")
        self.Select_class_cbb.setFont(font1)

        self.gridLayout_9.addWidget(self.Select_class_cbb, 1, 1, 1, 1)

        self.label_4 = QLabel(self.widget_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font1)

        self.gridLayout_9.addWidget(self.label_4, 1, 0, 1, 1)

        self.label_5 = QLabel(self.widget_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font1)

        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)

        self.Select_search_le = QLineEdit(self.widget_2)
        self.Select_search_le.setObjectName(u"Select_search_le")
        font3 = QFont()
        font3.setFamilies([u"\u5b8b\u4f53"])
        font3.setPointSize(11)
        self.Select_search_le.setFont(font3)
        self.Select_search_le.setFrame(True)

        self.gridLayout_9.addWidget(self.Select_search_le, 2, 1, 1, 1)

        self.label_6 = QLabel(self.widget_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font1)

        self.gridLayout_9.addWidget(self.label_6, 2, 0, 1, 1)

        self.gridLayout_9.setColumnStretch(0, 1)
        self.gridLayout_9.setColumnStretch(1, 6)

        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)

        self.widget_3 = QWidget(self.Sift_gb)
        self.widget_3.setObjectName(u"widget_3")
        self.horizontalLayout_2 = QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer = QSpacerItem(38, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.Select_update_pb = QPushButton(self.widget_3)
        self.Select_update_pb.setObjectName(u"Select_update_pb")
        self.Select_update_pb.setFont(font2)

        self.horizontalLayout_2.addWidget(self.Select_update_pb)

        self.horizontalSpacer_2 = QSpacerItem(38, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)


        self.gridLayout_3.addWidget(self.widget_3, 3, 0, 1, 1)

        self.widget = QWidget(self.Sift_gb)
        self.widget.setObjectName(u"widget")
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font1)

        self.horizontalLayout.addWidget(self.label_3)

        self.Image_num_le = QLineEdit(self.widget)
        self.Image_num_le.setObjectName(u"Image_num_le")
        self.Image_num_le.setFont(font1)

        self.horizontalLayout.addWidget(self.Image_num_le)

        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setFont(font1)

        self.horizontalLayout.addWidget(self.label)

        self.Image_total_l = QLabel(self.widget)
        self.Image_total_l.setObjectName(u"Image_total_l")
        self.Image_total_l.setFont(font1)

        self.horizontalLayout.addWidget(self.Image_total_l)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_4)

        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)

        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 55, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout_3.addItem(self.verticalSpacer, 4, 0, 1, 1)

        self.Select_image_spliter.addWidget(self.Sift_gb)

        self.gridLayout_8.addWidget(self.Select_image_spliter, 0, 0, 1, 1)


        self.horizontalLayout_6.addWidget(self.Sift_f)

        self.Sift_image_dw.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.Sift_image_dw)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.Edit_menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.Back_start_a)
        self.menu.addAction(self.menunew.menuAction())
        self.menu.addAction(self.menuopen.menuAction())
        self.menu.addAction(self.Save_a)
        self.menu.addAction(self.Save_as_a)
        self.menu.addAction(self.Exit_a)
        self.menunew.addAction(self.New_project_a)
        self.menunew.addAction(self.New_experiment_a)
        self.menuopen.addAction(self.Open_project_a)
        self.menuopen.addAction(self.Open_experiment_a)
        self.Edit_menu.addAction(self.Dataset_menu.menuAction())
        self.Edit_menu.addAction(self.Edit_net_a)
        self.Edit_menu.addAction(self.Classes_menu.menuAction())
        self.Edit_menu.addAction(self.Cfgs_init_a)
        self.Dataset_menu.addAction(self.Load_dataset_a)
        self.Dataset_menu.addAction(self.Load_zip_a)
        self.Dataset_menu.addAction(self.Create_dataset_a)
        self.Dataset_menu.addAction(self.Add_no_label_a)
        self.menu_3.addAction(self.menuarg.menuAction())
        self.menu_3.addAction(self.Show_result_curve_a)
        self.menu_3.addAction(self.Show_confusion_a)
        self.menu_3.addAction(self.Show_progress_a)
        self.menu_3.addAction(self.Show_sift_image_a)
        self.menuarg.addAction(self.Show_args_a)
        self.menuarg.addAction(self.Show_allargs_a)
        self.toolBar.addAction(self.Train_a)
        self.toolBar.addAction(self.Val_a)
        self.toolBar.addAction(self.Predict_a)
        self.toolBar.addAction(self.Export_a)

        self.retranslateUi(MainWindow)
        self.Show_args_a.triggered.connect(self.Args_dw.show)
        self.Show_progress_a.triggered.connect(self.Progress_dw.show)
        self.Show_result_curve_a.triggered.connect(self.Result_curve_dw.show)
        self.Show_confusion_a.triggered.connect(self.Confusion_dw.show)
        self.Show_sift_image_a.triggered.connect(self.Sift_image_dw.show)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Train_a.setText(QCoreApplication.translate("MainWindow", u"\u8bad\u7ec3", None))
#if QT_CONFIG(tooltip)
        self.Train_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u8bad\u7ec3", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.Train_a.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+T", None))
#endif // QT_CONFIG(shortcut)
        self.Val_a.setText(QCoreApplication.translate("MainWindow", u"\u9a8c\u8bc1", None))
#if QT_CONFIG(tooltip)
        self.Val_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u9a8c\u8bc1", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.Val_a.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+V", None))
#endif // QT_CONFIG(shortcut)
        self.Predict_a.setText(QCoreApplication.translate("MainWindow", u"\u9884\u6d4b", None))
#if QT_CONFIG(tooltip)
        self.Predict_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u9884\u6d4b", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.Predict_a.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+P", None))
#endif // QT_CONFIG(shortcut)
        self.Export_a.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
#if QT_CONFIG(tooltip)
        self.Export_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.Export_a.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.New_project_a.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee", None))
#if QT_CONFIG(shortcut)
        self.New_project_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.Open_project_a.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee", None))
#if QT_CONFIG(shortcut)
        self.Open_project_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.Save_a.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.Save_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.Save_as_a.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#if QT_CONFIG(shortcut)
        self.Save_as_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+S", None))
#endif // QT_CONFIG(shortcut)
        self.Exit_a.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#if QT_CONFIG(shortcut)
        self.Exit_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.Back_start_a.setText(QCoreApplication.translate("MainWindow", u"\u8fd4\u56de\u5f00\u59cb\u754c\u9762", None))
#if QT_CONFIG(shortcut)
        self.Back_start_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.Edit_net_a.setText(QCoreApplication.translate("MainWindow", u"\u795e\u7ecf\u7f51\u7edc", None))
#if QT_CONFIG(tooltip)
        self.Edit_net_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u795e\u7ecf\u7f51\u7edc", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.Edit_net_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.Show_args_a.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a", None))
#if QT_CONFIG(tooltip)
        self.Show_args_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a", None))
#endif // QT_CONFIG(tooltip)
        self.Show_allargs_a.setText(QCoreApplication.translate("MainWindow", u"\u66f4\u591a\u53c2\u6570", None))
#if QT_CONFIG(tooltip)
        self.Show_allargs_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u66f4\u591a\u53c2\u6570", None))
#endif // QT_CONFIG(tooltip)
        self.Show_confusion_a.setText(QCoreApplication.translate("MainWindow", u"\u6df7\u6dc6\u77e9\u9635\u663e\u793a\u5668", None))
#if QT_CONFIG(tooltip)
        self.Show_confusion_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a", None))
#endif // QT_CONFIG(tooltip)
        self.Show_result_curve_a.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u679c\u66f2\u7ebf\u663e\u793a\u5668", None))
#if QT_CONFIG(tooltip)
        self.Show_result_curve_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a", None))
#endif // QT_CONFIG(tooltip)
        self.Show_progress_a.setText(QCoreApplication.translate("MainWindow", u"\u8bad\u7ec3\u8fdb\u7a0b\u663e\u793a\u5668", None))
        self.Show_progress_a.setIconText(QCoreApplication.translate("MainWindow", u"\u6742\u9879\u663e\u793a\u5668", None))
#if QT_CONFIG(tooltip)
        self.Show_progress_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a", None))
#endif // QT_CONFIG(tooltip)
        self.New_experiment_a.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u9a8c", None))
#if QT_CONFIG(tooltip)
        self.New_experiment_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u5b9e\u9a8c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.New_experiment_a.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.Open_experiment_a.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u9a8c", None))
#if QT_CONFIG(tooltip)
        self.Open_experiment_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u5b9e\u9a8c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.Open_experiment_a.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.Show_sift_image_a.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7b5b\u9009\u5668", None))
#if QT_CONFIG(tooltip)
        self.Show_sift_image_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a", None))
#endif // QT_CONFIG(tooltip)
        self.Cfgs_init_a.setText(QCoreApplication.translate("MainWindow", u"\u53c2\u6570\u521d\u59cb\u5316", None))
#if QT_CONFIG(tooltip)
        self.Cfgs_init_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u521d\u59cb\u5316", None))
#endif // QT_CONFIG(tooltip)
        self.Load_dataset_a.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u8f7d", None))
#if QT_CONFIG(tooltip)
        self.Load_dataset_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u52a0\u8f7d", None))
#endif // QT_CONFIG(tooltip)
        self.Create_dataset_a.setText(QCoreApplication.translate("MainWindow", u"\u751f\u6210", None))
#if QT_CONFIG(tooltip)
        self.Create_dataset_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u751f\u6210", None))
#endif // QT_CONFIG(tooltip)
        self.Load_zip_a.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u538b\u7f29\u5305", None))
#if QT_CONFIG(tooltip)
        self.Load_zip_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u538b\u7f29\u5305", None))
#endif // QT_CONFIG(tooltip)
        self.Add_no_label_a.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0", None))
#if QT_CONFIG(tooltip)
        self.Add_no_label_a.setToolTip(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u672a\u6807\u6ce8\u6570\u636e", None))
#endif // QT_CONFIG(tooltip)
        self.Tool_show_pred_pb.setText(QCoreApplication.translate("MainWindow", u"P", None))
        self.Tool_show_true_pb.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.Tool_train_rb.setText(QCoreApplication.translate("MainWindow", u"train", None))
        self.Tool_val_rb.setText(QCoreApplication.translate("MainWindow", u"val", None))
        self.Tool_no_label_rb.setText(QCoreApplication.translate("MainWindow", u"no_label", None))
        self.Tool_results_rb.setText(QCoreApplication.translate("MainWindow", u"results", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menunew.setTitle(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa", None))
        self.menuopen.setTitle(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.Edit_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.Classes_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u79cd\u7c7b", None))
        self.Dataset_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u96c6", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menuarg.setTitle(QCoreApplication.translate("MainWindow", u"\u53c2\u6570\u7f16\u8f91\u5668", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.Progress_dw.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u8bad\u7ec3\u8fdb\u7a0b\u663e\u793a\u5668", None))
        self.Result_curve_dw.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u7ed3\u679c\u66f2\u7ebf\u663e\u793a\u5668", None))
        self.Args_dw.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u53c2\u6570\u7f16\u8f91\u5668", None))
        self.Confusion_dw.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u6df7\u6dc6\u77e9\u9635\u663e\u793a\u5668", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Confusion_denorm_w), QCoreApplication.translate("MainWindow", u"Denormalized", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Confusion_norm_w), QCoreApplication.translate("MainWindow", u"Normalized", None))
        self.Sift_image_dw.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7b5b\u9009\u5668", None))
        self.Sift_gb.setTitle(QCoreApplication.translate("MainWindow", u"\u7b5b\u9009", None))
        self.Select_ops_cbb.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.Select_ops_cbb.setItemText(1, QCoreApplication.translate("MainWindow", u"\u8f6c\u8bad\u7ec3\u96c6", None))
        self.Select_ops_cbb.setItemText(2, QCoreApplication.translate("MainWindow", u"\u8f6c\u9a8c\u8bc1\u96c6", None))
        self.Select_ops_cbb.setItemText(3, QCoreApplication.translate("MainWindow", u"\u8f6c\u672a\u6807\u6ce8\u96c6", None))

        self.Select_all_pb.setText(QCoreApplication.translate("MainWindow", u"\u5168\u9009", None))
        self.Select_batch_ops_pb.setText(QCoreApplication.translate("MainWindow", u"\u6279\u91cf\u6267\u884c", None))
        self.Select_dataset_cbb.setItemText(0, QCoreApplication.translate("MainWindow", u"\u603b\u6837\u672c\u96c6", None))
        self.Select_dataset_cbb.setItemText(1, QCoreApplication.translate("MainWindow", u"\u8bad\u7ec3\u96c6", None))
        self.Select_dataset_cbb.setItemText(2, QCoreApplication.translate("MainWindow", u"\u9a8c\u8bc1\u96c6", None))
        self.Select_dataset_cbb.setItemText(3, QCoreApplication.translate("MainWindow", u"\u672a\u6807\u6ce8\u96c6", None))
        self.Select_dataset_cbb.setItemText(4, QCoreApplication.translate("MainWindow", u"\u7ed3\u679c\u96c6", None))

        self.Select_class_cbb.setItemText(0, QCoreApplication.translate("MainWindow", u"all", None))

        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u79cd\u7c7b\uff1a", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u96c6\uff1a", None))
        self.Select_search_le.setInputMask("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22\uff1a", None))
        self.Select_update_pb.setText(QCoreApplication.translate("MainWindow", u"\u5237\u65b0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u5e8f\u53f7\uff1a", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"   /", None))
        self.Image_total_l.setText(QCoreApplication.translate("MainWindow", u"nn", None))
    # retranslateUi

